name: Build and Push Docker Image

on:
  push:
    branches:
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Meta
        id: meta
        run: |
          # Extract repository name in lowercase
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV  # Use $GITHUB_ENV to set the environment variable

          # Get version from Git tags or commit hash as fallback
          REPO_VERSION=$(git describe --tags --always)

          # Handle empty version
          if [ -z "$REPO_VERSION" ]; then
            REPO_VERSION=$(git rev-parse --short HEAD)
          fi

          echo "REPO_VERSION=${REPO_VERSION}" >> $GITHUB_ENV

          # Split version into major, minor, and patch (if possible)
          REPO_VERSION_MAJOR=$(echo ${REPO_VERSION} | awk -F"." '{print $1}')
          REPO_VERSION_MINOR=$(echo ${REPO_VERSION} | awk -F"." '{print $2}')
          REPO_VERSION_PATCH=$(echo ${REPO_VERSION} | awk -F"." '{print $3}')

          # Set defaults for minor and patch
          REPO_VERSION_MINOR=${REPO_VERSION_MINOR:-0}
          REPO_VERSION_PATCH=${REPO_VERSION_PATCH:-0}

          echo "REPO_VERSION_MAJOR=${REPO_VERSION_MAJOR}" >> $GITHUB_ENV
          echo "REPO_VERSION_MINOR=${REPO_VERSION_MAJOR}.${REPO_VERSION_MINOR}" >> $GITHUB_ENV
          echo "REPO_VERSION_PATCH=${REPO_VERSION_MAJOR}.${REPO_VERSION_MINOR}.${REPO_VERSION_PATCH}" >> $GITHUB_ENV          

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: app
          file: app/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64            
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/${{ env.REPO_NAME }}:${{ env.REPO_VERSION_PATCH }}-beta
            ${{ secrets.DOCKER_REGISTRY }}/${{ env.REPO_NAME }}:${{ env.REPO_VERSION_MINOR }}-beta
            ${{ secrets.DOCKER_REGISTRY }}/${{ env.REPO_NAME }}:${{ env.REPO_VERSION_MAJOR }}-beta
            ${{ secrets.DOCKER_REGISTRY }}/${{ env.REPO_NAME }}:beta
